config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  # resources :resumes
  get 'resumes/phone_autocomplete', to: 'resumes#phone_autocomplete', as: :resumes_phone_autocomplete
  get 'resumes/email_autocomplete', to: 'resumes#email_autocomplete', as: :resumes_email_autocomplete
  get 'resumes/get_summary_by_id', to: 'resumes#get_summary_by_id', as: :resumes_get_summary_by_id

  get 'employees/autocomplete', to: 'employees#employees_autocomplete', as: :employees_autocomplete
  post 'extract_from_resume', to: 'resumes#extract_from_resume' 
  post 'employees/edit_slot', to: 'employees#edit_slot'
  match 'login', to: 'employees#login'                                         , via: :post
  match 'logout', to: 'employees#logout'                                       , via: :get
  match 'requirements/my_requirements', to: 'requirements#my_requirements'     , via: :get
  match 'requirements/req_analysis', to: 'requirements#req_analysis'           , via: :get
  match 'requirements/all_reqs', to: 'requirements#all_reqs'                   , via: :get
  match 'requirements/search', to: 'requirements#search'                       , via: :post
  match 'requirements/close_requirement', to: 'requirements#close_requirement' , via: :post
  resources :requirements
  match 'add_interviewer', to: 'interview_skills#add_interviewer'              ,via: :post
  match 'interview_skills/create', to: 'interview_skills#create'                             ,via: :post
  match 'interview_skills/:id', to: 'interview_skills#destroy'                                       , via: :delete
  match 'home/interview-panels', to: 'home#interview_panels'                                       , via: :get
  match 'home/search', to: 'home#search'                                       , via: :post
  match 'home/search', to: 'home#search'                                       , via: :get
  match 'home/show_summary_per_interviewer', to:'home#show_summary_per_interviewer'                                       , via: :get
  match 'home/show_summary_per_recruiter', to: 'home#show_summary_per_recruiter'                                     , via: :get

  match 'home/show_summary_per_manager', to: 'home#show_summary_per_manager'                                     , via: :get
  match 'home/actions', to: 'home#actions'                                     , via: :get
  match 'home/advanced_search_results', to: 'home#advanced_search_results'     , via: :get
  match 'home/advanced_search', to: 'home#advanced_search'          , via: :get
  match 'home/actions_page', to: 'home#actions_page'                , via: :get
  match 'home/dashboard', to: 'home#dashboard'                      , via: :get
  match 'home/summaries', to: 'home#summaries'                      , via: :get
  match 'designations/index', to: 'designations#index'              , via: :get
  match 'groups/index', to: 'groups#index'                          , via: :get
  match 'portals/index', to: 'portals#index'                        , via: :get
  match 'agencies/index', to: 'agencies#index'                      , via: :get
  match 'resumes/new_resumes', to: 'resumes#new_resumes'            , via: :get
  match 'resumes/inbox',to: 'resumes#inbox'                         , via: :get
  match 'resumes/outbox',to: 'resumes#outbox'                       , via: :get
  match 'resumes/trash',to: 'resumes#trash'                         , via: :get
  match 'resumes/resume_action',to: 'resumes#resume_action'         , via: :post
  match 'resumes/add_hr_comment',to: 'resumes#add_hr_comment'       , via: :post
  match 'resumes/eng_select',to: 'resumes#eng_select'               , via: :get
  match 'resumes/hac',to: 'resumes#hac'                             , via: :get
  match 'resumes/send_for_eng_decision',to:'resumes#send_for_eng_decision'   , via: :post
  match 'resumes/send_for_decision',to: 'resumes#send_for_decision'          , via: :post
  match 'resumes/manager_eng_select',to: 'resumes#manager_eng_select'        , via: :get
  match 'resumes/manager_hac',to: 'resumes#manager_hac'                      , via: :get
  match 'resumes/manage_interviews',to: 'resumes#manage_interviews'          , via: :post
  match 'resumes/show_resume_comments',to: 'resumes#show_resume_comments'    , via: :post
  match 'resumes/export_as_xls',to: 'resumes#export_as_xls'                  , via: :get
  match 'resumes/export_interviews',to: 'resumes#export_interviews'          , via: :get
  match 'resumes/find_resume_within_given_dates',to: 'resumes#find_resume_within_given_dates' , via: :get
  match 'employees/list_my_employees',to: 'employees#list_my_employees'          , via: :get
  match 'employees/change_to',to: 'employees#change_to'                          , via: :get
  match 'resumes/export_as_xls_requirement',to:'resumes#export_as_xls_requirement' , via: :get
  match 'resumes/export_as_xls_requirement_for_shortlisted',to: 'resumes#export_as_xls_requirement_for_shortlisted', via: :get
  match 'resumes/export_as_xls_requirement_for_forwards',to: 'resumes#export_as_xls_requirement_for_forwards'      , via: :get
  match 'resumes/export_as_xls_requirement_for_offered',to: 'resumes#export_as_xls_requirement_for_offered'        , via: :get 
  match 'resumes/export_as_xls_requirement_for_yto',to: 'resumes#export_as_xls_requirement_for_yto'                , via: :get 
  match 'resumes/export_as_xls_requirement_for_scheduled',to: 'resumes#export_as_xls_requirement_for_scheduled'    , via: :get
  match 'resumes/export_as_xls_requirement_for_rejected',to: 'resumes#export_as_xls_requirement_for_rejected'      , via: :get
  match 'resumes/export_as_xls_requirement_for_hold',to: 'resumes#export_as_xls_requirement_for_hold'              , via: :get
  match 'resumes/export_as_xls_requirement_for_joining',to: 'resumes#export_as_xls_requirement_for_joining'        , via: :get
  match 'resumes/xport_as_xls_all_uploaded_resumes',to: 'resumes#export_as_xls_all_uploaded_resumes'               , via: :get  
  match 'resumes/joined',to: 'resumes#joined'                , via: :get
  match 'resumes/upload_document',to: 'resumes#upload_document'         , via: :post
  match 'get_resume_attachment', to: 'resumes#get_resume_attachment'    , via: :get 
  match 'resumes/show/:id',to: 'resumes#show'                , via: :get
  match 'resumes/hold',to: 'resumes#hold'                    , via: :get
  match 'resumes/offered',to: 'resumes#offered'              , via: :get
  match 'resumes/rejected',to: 'resumes#rejected'            , via: :get
  match 'resumes/future',to: 'resumes#future'                , via: :get
  match 'resumes/submit_ph_rating',to: 'resumes#submit_ph_rating'                , via: :post
  match 'resumes/interview_requests',to: 'resumes#interview_requests'       , via: :get
  match 'resumes/get_interviews',to: 'resumes#get_interviews'               , via: :get
  match 'resumes/download_resume',to: 'resumes#download_resume'             , via: :get
  match 'resumes/delete_resume',to: 'resumes#delete_resume'                 , via: :delete, as: :delete_resume
  match 'resumes/manager_joined',to: 'resumes#manager_joined'               , via: :get
  match 'resumes/manager_offered',to: 'resumes#manager_offered'             , via: :get
  match 'resumes/manager_hold',to: 'resumes#manager_hold'                   , via: :get
  match 'resumes/shortlisted',to: 'resumes#shortlisted'                     , via: :get
  match 'resumes/forwarded',to: 'resumes#forwarded'                         , via: :get
  match 'resumes/new_resumes',to: 'resumes#new_resumes'                     , via: :get
  match 'resumes/interviews_status',to: 'resumes#interviews_status'         , via: :get
  match 'resumes/interviews_status_new',to: 'resumes#interviews_status_new' , via: :get
  match 'resumes/manager_index',to: 'resumes#manager_index'                 , via: :get
  match 'resumes/manager_shortlisted',to: 'resumes#manager_shortlisted'     , via: :get
  match 'resumes/manager_rejected',to: 'resumes#manager_rejected'           , via: :get
  match 'resumes/manager_interviews_status',to: 'resumes#manager_interviews_status'   , via: :get
  match 'resumes/interview_calendar',to: 'resumes#interview_calendar'       , via: :get
  match 'resumes/get_interviews',to: 'resumes#get_interviews'               , via: :get 
  match 'resumes/my_resumes',to: 'resumes#my_resumes'                       , via: :get
  match 'resumes/recent',to: 'resumes#recent'                               , via: :get
  match 'resumes/find_resume_in_given_date',to: 'resumes#find_resume_in_given_date'   , via: :get
  match 'resumes/upload_xls',to: 'resumes#upload_xls'                                 , via: :get
  match 'resumes/update_resume_likely_to_join',to: 'resumes#update_resume_likely_to_join'     , via: :get
  match 'resumes/process_xls_and_zipped_resumes',to: 'resumes#process_xls_and_zipped_resumes' , via: :get
  match 'resumes/close_requirement',to: 'resumes#close_requirement'                           , via: :get
  match 'resumes/export_interviews_per_date',to: 'resumes#export_interviews_per_date'         , via: :get
  match 'resumes/yto',to: 'resumes#yto'                                                       , via: :get
  match 'resumes/manager_yto',to: 'resumes#manager_yto'                                       , via: :get
  match 'resumes/show_quarterly_joined',to: 'resumes#show_quarterly_joined'                   , via: :get
  match 'resumes/show_all_joined_or_not_joined',to: 'resumes#show_all_joined_or_not_joined'   , via: :get
  match 'resumes/show_quarterly_offered',to: 'resumes#show_quarterly_offered'                 , via: :get
  match 'resumes/show_all_offered',to: 'resumes#show_all_offered'                             , via: :get
  match 'resumes/show_quarterly_not_accepted',to: 'resumes#show_quarterly_not_accepted'       , via: :get

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to              :employee
  belongs_to              :designation
  has_many                :interviews
  has_many                :req_matches
  has_and_belongs_to_many :forwards
  has_and_belongs_to_many :accounts
  belongs_to              :group,
                          :class_name  => "Group",
                          :foreign_key => "group_id"
  belongs_to              :posted_by,
                          :class_name  => "Employee",
                          :foreign_key => "posting_emp_id"

  belongs_to              :scheduling_emp,
                          :optional => true,
                          :class_name => "Employee",
                          :foreign_key => "scheduling_employee_id"
  belongs_to              :ta_lead,
                          :optional => true,
                          :class_name => "Employee",
                          :foreign_key => "ta_lead_id"
  belongs_to              :eng_lead,
                          :optional => true,
                          :class_name => "Employee",
                          :foreign_key => "eng_lead_id"

  # Presence stuff
  validates_presence_of :name
  validates_presence_of :employee_id
  validates_presence_of :designation_id
  validates_presence_of :group_id

  # Uniqueness stuff
  validates_uniqueness_of :name

  def Requirement.get_experience_array
    exp_array = []
    for i in 1..20
      exp_array << i
    end

    exp_array
  end

  def Requirement.get_requirement_array_for_select
    req_array = []
    all_ordered_requirements = Requirement.all.order(:name)
    all_open_requirements = all_ordered_requirements.find_all {
      |req| req.status == "OPEN"
    }
    all_open_requirements.each do |req|
      req_array.push([req.name, req.id])
    end
    req_array
  end

  def Requirement.get_all_requirement_array_for_select
    req_array = []
    req_array.push(["Select Req", 0])
    all_ordered_requirements = Requirement.all.order(:name)
    all_ordered_requirements.each do |req|
      req_array.push([req.name, req.id])
    end
    req_array
  end

  def Requirement.get_employee_requirement_array(employee)
    emp_req_array = []
    employee.requirements.each do |req|
      emp_req_array.push([req.name, req.id])
    end
    emp_req_array
  end

  def open_forwards
    self.forwards.find_all { |f|
      f.status == "FORWARDED"
    }
  end

  def shortlists
    self.req_matches.find_all { |r|
      r.status == "SHORTLISTED"
    }
  end

  def scheduled
    self.req_matches.find_all { |r|
      r.status == "SCHEDULED" &&
      r.resume.resume_overall_status != "Future"
    }
  end

  def rejected
    # Find forward's rejected also
    self.req_matches.find_all { |r|
      r.status == "REJECTED"
    }
  end

  def yto
    self.req_matches.where(status: "YTO")
  end

  def hold
    self.req_matches.find_all { |r|
      r.status == "HOLD"
    }
  end

  def offered
    self.req_matches.find_all { |r|
      r.status == "OFFERED"
    }
  end

  def joining
    self.req_matches.find_all { |r|
      r.status        == "JOINING" &&
      r.resume.resume_overall_status == "Joining Date Given"
    }
  end

  def Requirement.open_requirements
    Requirement.all.find_all { |r|
      r.status == "OPEN"
    }
  end

  def isOPEN?
    if self.status == "OPEN"
      return true
    else
      return false
    end
  end

  def name_for_js
    if name
      return name.gsub(/'|"/, '')
    else
      return name
    end
  end

end

app/helpers/requirement_helper.rb
module RequirementHelper
  def get_forwards_count(req)
    req.forwards.where(status:"FORWARDED").count()
  end 
  def get_shortlisted_count(req)
    req.req_matches.where(status:"SHORTLISTED").count()
  end 
end

app/views/requirements/_req_analysis.html.erb
<% if !@partial %>
  <div id="cost_top" class="common_class">
<% end %>
<div id="analysis">
  <%= render "shared/arrow_links", :controller => "requirements", :action => "req_analysis", :update => "analysis" %>
  <% @req_analysis.each do |group, analysis| %>
    <%= link_to group.name.titleize,'#',          :onclick => "showHide(this);", :id     => "font_14" %>
    <%= render "requirements/req_analysis_type_table", :object  => analysis,          :id_var => group.name.split(" ")[0].downcase %> <br /> <br />
  <% end %>

</div>
<% if !@partial %>
  </div>
<% end %>

app/views/requirements/_req_analysis_type_table.html.erb
<table id="req_analysis_<%= id_var %>_table">
  <tr class="header_row">
    <th> Designation Name  </th>
    <% @smonth.upto @emonth do |month| %>
      <th class="align_middle"> <%= month  %>/<%= @year %> </th>
    <% end %>
  </tr>
  <% object.each do |desg, row| %>
    <tr class="<%= cycle('color_line_odd', 'color_line_even') %>">
      <td> <%= desg[:name] %> </td>
      <% row.each do |r| %>
        <% unless r.nil? %>
          <% if r == 0 %>
            <td> <%= r %> </td>
          <% else %>
            <td class="text_as_red"> <%= r %> </td>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/requirements/_requirement_form.html.erb
<br /> <br />
<%= form_for(@requirement, :url => url_for(:host => APP_CONFIG['host_name'], :controller => "requirements", :action => (button_tag == "Update" ? "update" : "create")), :html => {:method => (button_tag == "Update" ? "put" : "post")}) do |f|%>

  <%if @requirement%>
  <%  if @requirement.exp%>
 <%     exp      = @requirement.exp.split("-")%>
  <%    min_exp  = exp[0]%>
  <%    max_exp  = exp[1]%>
  <%  end%>

  <%  status   = @requirement.status%>
  <%  req_type = @requirement.req_type%>
  <%  nop      = @requirement.nop%>
  <%  sdate    = date_in_calendar_format(@requirement.sdate) if @requirement.sdate%>
  <%  edate    = date_in_calendar_format(@requirement.edate) if @requirement.edate%>
  <%else%>
  <%  min_exp  = max_exp = status = req_type = sdate = edate = nop = ""%>
  <%end%>
  <% if @requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul>
      <% @requirement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table id="req_form_table">
    <tr>
      <td> Requirement name </td>
      <td> <%= f.text_field :name %> </td>
    </tr>
    <tr>
      <td> Number of positions </td>
      <td>
        <%= select_tag "requirement[nop]", options_for_select(get_experience_years, nop) %>
      </td>
    </tr>
    <tr>
      <td> Position Name </td>
      <td> <%= collection_select(:requirement, :designation_id, @designations, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
    <tr>
      <td> Requirement skills </td>
      <td> <%= f.text_area :skill %> </td>
    </tr>
    <tr>
      <td> Requirement description </td>
      <td> <%= f.text_area :description %> </td>
    </tr>
    <tr>
      <td> Management comment </td>
      <td> <%= f.text_area :mgt_comment %> </td>
    </tr>
    <tr>
      <td> Start Date </td>
      <td><%= f.text_field :sdate, :class => "datepicker" %></td>
    </tr>
    <tr>
      <td> End Date </td>
      <td><%= f.text_field :edate, :class => "datepicker" %></td>
  </tr>
    <tr>
      <td> Required Experience </td>
      <td class="two_dropdownlist_single_td">
        <%= select_tag "req[min_exp]", options_for_select(get_experience_years, min_exp.to_i) %> Min
        <%= select_tag "req[max_exp]", options_for_select(get_experience_years, max_exp.to_i) %> Max
      </td>
    </tr>
    <tr>
      <td> Group </td>
      <td> <%= collection_select(:requirement, :group_id, @groups, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
    <tr>
      <td> Customer </td>
      <td>
        <div class="multi_selected_qualification">
          <table id="customer_list_table">
            <tr>
              <% count = 0 %>
              <% for acc in @accounts %>
                <% recordVal = acc.name %>
                <% if count < 3 %>
                  <td>
                    <% if @requirement.accounts.include?(acc) %>
                      <div class="one_element_div_qual" id="one_element_div_qual_<%= acc.id %>" style="background-color: #ffffff;">
                        <input type="checkbox" id="qual_checkbox_<%= acc.id %>" name="account_ids[]" value="<%= acc.id %>" checked="checked" class="input_with_low_width"/>
                    <% else %>
                      <div class="one_element_div_qual" id="one_element_div_qual_<%= acc.id %>">
                        <input type="checkbox" id="qual_checkbox_<%= acc.id %>" name="account_ids[]" value="<%= acc.id %>" class="input_with_low_width"/>
                    <% end %>
                      <label for="qual_checkbox_<%= acc.id %>"> <%= recordVal.titleize %> </label>
                    </div>
                  </td>
                  <% count = count + 1 %>
                <% else %>
                  </tr> <tr>
                  <td>
                    <% if @requirement.accounts.include?(acc) %>
                      <div class="one_element_div_qual" id="one_element_div_qual_<%= acc.id %>" style="background-color: #ffffff;">
                        <input type="checkbox" id="qual_checkbox_<%= acc.id %>" name="account_ids[]" value="<%= acc.id %>" checked="checked" class="input_with_low_width"/>
                    <% else %>
                      <div class="one_element_div_qual" id="one_element_div_qual_<%= acc.id %>">
                        <input type="checkbox" id="qual_checkbox_<%= acc.id %>" name="account_ids[]" value="<%= acc.id %>" class="input_with_low_width"/>
                    <% end %>
                      <label for="qual_checkbox_<%= acc.id %>"> <%= recordVal.titleize %> </label>
                    </div>
                  </td>
                  <% count = 1 %>
                <% end %>
              <% end %>
            </tr>
          </table>
        </div>
      </td>
    </tr>
    <tr>
      <td> Manager </td>
      <td> <%= collection_select(:requirement, :employee_id, @employees, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
    <tr>
      <td> Source owner </td>
      <td> <%= collection_select(:requirement, :source_owner, @ta_employees, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
    <tr>
      <td> Schedule owner </td>
      <td> <%= collection_select(:requirement, :schedule_owner, @ta_employees, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
    <tr>
      <td> TA Lead </td>
      <td> <%= collection_select(:requirement, :ta_lead_id, @ta_employees, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
    <tr>
      <td> Eng Lead </td>
      <td> <%= collection_select(:requirement, :eng_lead_id, @employees, :id, :name, { :prompt => "Please Select" }) %> </td>
    </tr>
      <tr>
      <td> Requirement status   </td>
      <td> <%= select_tag "requirement[status]", options_for_select([["Open", "OPEN"], ["Hold", "HOLD"], ["Closed - Expired", "CLOSED EXPIRED"], ["Closed - Offered", "CLOSED OFFERED"], ["Closed - Joining", "CLOSED JOINING"], ["Closed - Delete", "CLOSED DELETE"] ], status) %> </td>
    </tr>
    <tr>
      <td> Requirement type     </td>
      <td> <%= select_tag "requirement[req_type]", options_for_select([["Ordinary", "ORDINARY"], ["Hot", "HOT"]], req_type) %> </td>
    </tr>
    <tr>
      <td> &nbsp; </td>
      <td class="requirement_submit_button"> <%= f.submit("#{button_tag}") %> </td>
    </tr>
  </table>
<% end %>
<br /> <br />
<%= link_to "List of requirements", :host => APP_CONFIG['host_name'], :controller => "requirements", :style => "color: #0000FF;" %>
<script>
  $(function() {
  $('.datepicker').datepicker({
        dateFormat: 'dd-mm-yy',
        showOn: "button",
        buttonImage: "/assets/calendar.gif",
        buttonImageOnly: true,
        buttonText: "Select date"
      });
});
</script>

app/views/requirements/_show_description.html.erb
<div id="show_requirements_description_div_<%= @status %>">
  <span class="span_with_13_with_padding_0"> <%= @status.titleize %>
    (<%= (@render == "manager_index") ? @forwards.size : @matches.size %>)
  </span>
  <% action = "export_as_xls_requirement_for_" + @status.downcase %>
  <%= link_to "Export", :host => APP_CONFIG['host_name'], :controller => "resumes", :action => action, :requirement_id => @requirement.id, :for_status => @status %>
  <% render_type = (@render == "interview_table") ? @render : "shared_" + @render %>
  <span class="span_with_padding_0_float">
    <%= link_to "Export", :host => APP_CONFIG['host_name'], :controller => "resumes", :action => action, :requirement_id => @requirement.id, :for_status => @status %>
  </span>
  <%= render "resumes/#{render_type}" %>
</div>

app/views/requirements/edit.html.erb
<div id="req_update_div" class="common_class">
  <span> Updating Requirement </span>
  <%= render "requirement_form", :class_label => "requirement_update_label", :class_field => "requirement_update_field", :button_tag => "Update" %>
</div>

app/views/requirements/index.html.erb
<% only_my_requirement = (params[:action] == "my_requirements") ? true : false %>

<div id="req_list_div" class="common_class">
  <div class="float_left">
    <span> Requirements : <%= @requirements.size %></span><br /><br />
    <div class="background_green"> Closed Requirements </div>
    <div class="background_red"> Hot Requirements </div>
  </div>
  <% if only_my_requirement %>
    <div class="add_link" style="padding-right: 10px; padding-left: 10px;">
      <%= link_to "ON HOLD", :host => APP_CONFIG['host_name'], :controller => "requirements", :action => "my_requirements" , :status => "hold" %>
    </div>
    <div class="add_link" style="padding-right: 10px; padding-left: 10px;">
      <%= link_to "OPEN", :host => APP_CONFIG['host_name'], :controller => "requirements", :action => "my_requirements" , :status => "open" %>
    </div>
    <div class="add_link" style="padding-right: 10px; padding-left: 10px;">
      <%= link_to "ALL", :host => APP_CONFIG['host_name'], :controller => "requirements", :action => "my_requirements" , :status => "any" %>
    </div>
  <% end %>
  <% if is_ADMIN? %>
    <div class="add_link" style="padding-left: 10px;">
      <%= link_to "Requirement Analysis", :host => APP_CONFIG['host_name'], :action => "req_analysis" %>
    </div>
  <% end %>
  <% if is_HR_ADMIN? || is_RMS_ANALYST? %>
    <div class="add_link" style="padding-right: 10px; padding-left: 10px;">
      <%= link_to "Add new requirement", :host => APP_CONFIG['host_name'], :controller => "requirements", :action => "new" %>
    </div>
  <% end %>
  <% if is_HR_ADMIN? %>
    <div class="add_link" style="padding-right: 10px;">
      <% if params[:action] == "index" %>
        <%= link_to "All requirements", :host => APP_CONFIG['host_name'], :action => "all_reqs" %>
      <% else %>
        <%= link_to "All Active requirements", :host => APP_CONFIG['host_name'], :action => "index" %>
      <% end %>
    </div>
  <% end %>
  <br />
  <br />
  <% if !only_my_requirement %>
    <div class="add_link float-md-right col-md-2">
      <%= form_tag :host => APP_CONFIG['host_name'], :action => "search" do %>
        <%= text_field_tag :search, params[:search], :onfocus => 'fillRequirementSearchBoxWithContents()', :placeholder => "Search reqs by employee name" %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  <% end %>
  <br>
  <br /> <br />

  <%= form_tag(:host => APP_CONFIG['host_name'], :controller => "requirements", :action => "close_requirement") do %>      
    <table>
      <tr class="header_row">
        <td> Requirement ID </td>
        <td> Name             </td>
        <td> Skills/Desc      </td>
        <td style="width:75px;"> Exp </td>
        <td> End              </td>
        <td> Positions        </td>
        <% if !only_my_requirement %>
          <td> Owner            </td>
        <% else %>
          <td> Forwards     </td>
          <td> Shortlists    </td>
        <% end %>
        <%if is_HR_ADMIN? %>
          <td> <%= (@requirements.size != 0) ? submit_tag('Delete') : "Delete"  %> </td>
        <%end%>
      </tr>
      <% @requirements.each do |requirement| %>
        <% if requirement.status != "OPEN" %>
          <tr style="background: #9df405;">
        <% elsif requirement.req_type == "HOT" %>
          <tr style="background: #FF8080;">
        <% else %>
          <tr class="<%= cycle('color_line_odd', 'color_line_even') %>">
        <% end %>
        <td>
        <%= requirement.id %>
        </td>
        <td>
        <%= get_requirement_link_with_mouse_over_and_mouseout(requirement) %>
        </td>
        <td title = "<%= requirement.skill %> <%= requirement.description %>" >
          <%= snippet(requirement.skill, 5) %> <br />
        </td>
        <td>
          <%= requirement.exp.gsub(/ /,"") %> ( <%= requirement.designation.name %> )
        </td>
        <td>
          <% if requirement.edate %>
            <%= print_date(requirement.edate) %>
          <% end %>
        </td>
        <td>
          <%= requirement.nop %> 
        </td>
        <% if !only_my_requirement %>
          <td>
            <%= get_words(requirement.employee.name, 1) %>
          </td>
        <% else %>
          <td>
            <%= get_forwards_count(requirement) %> 
          </td>
          <td>
            <%= get_shortlisted_count(requirement) %>
          </td>
        <% end %>
        <%if is_HR_ADMIN? %>
          <td> <%= check_box("req", "commands", {:multiple => true}, requirement.id, nil) %>    </td>
        <%end%>
        </tr>
      <% end %>
    </table>
  <% end %>
 <br /> <br />
</div>

app/views/requirements/new.html.erb
<div id="req_create_div" class="common_class">
  <span> Adding Requirement </span>
  <%= render "requirement_form", :class_label => "requirement_create_label", :class_field => "requirement_create_field", :button_tag => "GO" %>
</div>

app/views/requirements/req_analysis.html.erb
<%= render "req_analysis"%>

app/views/requirements/show_brief.html.erb
<div id="req_breif_details_div" class="common_class">
  <span class="span_with_13_with_padding_0"> <%= @requirement.name %> </span>
  <br /> <br />
  <table id="req_breif_details_table">
    <tr>
      <td> Skills required for this position - </td>
      <td> <%= @requirement.skill %> </td>
    </tr>
    <tr>
      <td> Job description for this position - </td>
      <td> <%= @requirement.description %> </td>
    </tr>
    <tr>
      <td> Experience required for this position - </td>
      <td> <%= @requirement.exp %> yrs </td>
    </tr>
    <tr>
      <td> Requirement owner - </td>
      <td> <%= @requirement.employee.name %> </td>
    </tr>
    <tr>
      <td> Group - </td>
      <td> <%= @requirement.group.name %> </td>
    </tr>
    <tr>
      <td> Type - </td>
      <td> <%= @requirement.req_type %> </td>
    </tr>
  </table>
  <br /> <br />
  <%= link_to "List of requirements", :host => APP_CONFIG['host_name'], :controller => "requirements", :style => "color: #0000FF;" %> </div>
</div>