config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  # resources :resumes
  get 'resumes/phone_autocomplete', to: 'resumes#phone_autocomplete', as: :resumes_phone_autocomplete
  get 'resumes/email_autocomplete', to: 'resumes#email_autocomplete', as: :resumes_email_autocomplete
  get 'resumes/get_summary_by_id', to: 'resumes#get_summary_by_id', as: :resumes_get_summary_by_id

  get 'employees/autocomplete', to: 'employees#employees_autocomplete', as: :employees_autocomplete
  post 'extract_from_resume', to: 'resumes#extract_from_resume' 
  post 'employees/edit_slot', to: 'employees#edit_slot'
  match 'login', to: 'employees#login'                                         , via: :post
  match 'logout', to: 'employees#logout'                                       , via: :get
  match 'requirements/my_requirements', to: 'requirements#my_requirements'     , via: :get
  match 'requirements/req_analysis', to: 'requirements#req_analysis'           , via: :get
  match 'requirements/all_reqs', to: 'requirements#all_reqs'                   , via: :get
  match 'requirements/search', to: 'requirements#search'                       , via: :post
  match 'requirements/close_requirement', to: 'requirements#close_requirement' , via: :post
  resources :requirements
  match 'add_interviewer', to: 'interview_skills#add_interviewer'              ,via: :post
  match 'interview_skills/create', to: 'interview_skills#create'                             ,via: :post
  match 'interview_skills/:id', to: 'interview_skills#destroy'                                       , via: :delete
  match 'home/interview-panels', to: 'home#interview_panels'                                       , via: :get
  match 'home/search', to: 'home#search'                                       , via: :post
  match 'home/search', to: 'home#search'                                       , via: :get
  match 'home/show_summary_per_interviewer', to:'home#show_summary_per_interviewer'                                       , via: :get
  match 'home/show_summary_per_recruiter', to: 'home#show_summary_per_recruiter'                                     , via: :get

  match 'home/show_summary_per_manager', to: 'home#show_summary_per_manager'                                     , via: :get
  match 'home/actions', to: 'home#actions'                                     , via: :get
  match 'home/advanced_search_results', to: 'home#advanced_search_results'     , via: :get
  match 'home/advanced_search', to: 'home#advanced_search'          , via: :get
  match 'home/actions_page', to: 'home#actions_page'                , via: :get
  match 'home/dashboard', to: 'home#dashboard'                      , via: :get
  match 'home/summaries', to: 'home#summaries'                      , via: :get
  match 'designations/index', to: 'designations#index'              , via: :get
  match 'groups/index', to: 'groups#index'                          , via: :get
  match 'portals/index', to: 'portals#index'                        , via: :get
  match 'agencies/index', to: 'agencies#index'                      , via: :get
  match 'resumes/new_resumes', to: 'resumes#new_resumes'            , via: :get
  match 'resumes/inbox',to: 'resumes#inbox'                         , via: :get
  match 'resumes/outbox',to: 'resumes#outbox'                       , via: :get
  match 'resumes/trash',to: 'resumes#trash'                         , via: :get
  match 'resumes/resume_action',to: 'resumes#resume_action'         , via: :post
  match 'resumes/add_hr_comment',to: 'resumes#add_hr_comment'       , via: :post
  match 'resumes/eng_select',to: 'resumes#eng_select'               , via: :get
  match 'resumes/hac',to: 'resumes#hac'                             , via: :get
  match 'resumes/send_for_eng_decision',to:'resumes#send_for_eng_decision'   , via: :post
  match 'resumes/send_for_decision',to: 'resumes#send_for_decision'          , via: :post
  match 'resumes/manager_eng_select',to: 'resumes#manager_eng_select'        , via: :get
  match 'resumes/manager_hac',to: 'resumes#manager_hac'                      , via: :get
  match 'resumes/manage_interviews',to: 'resumes#manage_interviews'          , via: :post
  match 'resumes/show_resume_comments',to: 'resumes#show_resume_comments'    , via: :post
  match 'resumes/export_as_xls',to: 'resumes#export_as_xls'                  , via: :get
  match 'resumes/export_interviews',to: 'resumes#export_interviews'          , via: :get
  match 'resumes/find_resume_within_given_dates',to: 'resumes#find_resume_within_given_dates' , via: :get
  match 'employees/list_my_employees',to: 'employees#list_my_employees'          , via: :get
  match 'employees/change_to',to: 'employees#change_to'                          , via: :get
  match 'resumes/export_as_xls_requirement',to:'resumes#export_as_xls_requirement' , via: :get
  match 'resumes/export_as_xls_requirement_for_shortlisted',to: 'resumes#export_as_xls_requirement_for_shortlisted', via: :get
  match 'resumes/export_as_xls_requirement_for_forwards',to: 'resumes#export_as_xls_requirement_for_forwards'      , via: :get
  match 'resumes/export_as_xls_requirement_for_offered',to: 'resumes#export_as_xls_requirement_for_offered'        , via: :get 
  match 'resumes/export_as_xls_requirement_for_yto',to: 'resumes#export_as_xls_requirement_for_yto'                , via: :get 
  match 'resumes/export_as_xls_requirement_for_scheduled',to: 'resumes#export_as_xls_requirement_for_scheduled'    , via: :get
  match 'resumes/export_as_xls_requirement_for_rejected',to: 'resumes#export_as_xls_requirement_for_rejected'      , via: :get
  match 'resumes/export_as_xls_requirement_for_hold',to: 'resumes#export_as_xls_requirement_for_hold'              , via: :get
  match 'resumes/export_as_xls_requirement_for_joining',to: 'resumes#export_as_xls_requirement_for_joining'        , via: :get
  match 'resumes/xport_as_xls_all_uploaded_resumes',to: 'resumes#export_as_xls_all_uploaded_resumes'               , via: :get  
  match 'resumes/joined',to: 'resumes#joined'                , via: :get
  match 'resumes/upload_document',to: 'resumes#upload_document'         , via: :post
  match 'get_resume_attachment', to: 'resumes#get_resume_attachment'    , via: :get 
  match 'resumes/show/:id',to: 'resumes#show'                , via: :get
  match 'resumes/hold',to: 'resumes#hold'                    , via: :get
  match 'resumes/offered',to: 'resumes#offered'              , via: :get
  match 'resumes/rejected',to: 'resumes#rejected'            , via: :get
  match 'resumes/future',to: 'resumes#future'                , via: :get
  match 'resumes/submit_ph_rating',to: 'resumes#submit_ph_rating'                , via: :post
  match 'resumes/interview_requests',to: 'resumes#interview_requests'       , via: :get
  match 'resumes/get_interviews',to: 'resumes#get_interviews'               , via: :get
  match 'resumes/download_resume',to: 'resumes#download_resume'             , via: :get
  match 'resumes/delete_resume',to: 'resumes#delete_resume'                 , via: :delete, as: :delete_resume
  match 'resumes/manager_joined',to: 'resumes#manager_joined'               , via: :get
  match 'resumes/manager_offered',to: 'resumes#manager_offered'             , via: :get
  match 'resumes/manager_hold',to: 'resumes#manager_hold'                   , via: :get
  match 'resumes/shortlisted',to: 'resumes#shortlisted'                     , via: :get
  match 'resumes/forwarded',to: 'resumes#forwarded'                         , via: :get
  match 'resumes/new_resumes',to: 'resumes#new_resumes'                     , via: :get
  match 'resumes/interviews_status',to: 'resumes#interviews_status'         , via: :get
  match 'resumes/interviews_status_new',to: 'resumes#interviews_status_new' , via: :get
  match 'resumes/manager_index',to: 'resumes#manager_index'                 , via: :get
  match 'resumes/manager_shortlisted',to: 'resumes#manager_shortlisted'     , via: :get
  match 'resumes/manager_rejected',to: 'resumes#manager_rejected'           , via: :get
  match 'resumes/manager_interviews_status',to: 'resumes#manager_interviews_status'   , via: :get
  match 'resumes/interview_calendar',to: 'resumes#interview_calendar'       , via: :get
  match 'resumes/get_interviews',to: 'resumes#get_interviews'               , via: :get 
  match 'resumes/my_resumes',to: 'resumes#my_resumes'                       , via: :get
  match 'resumes/recent',to: 'resumes#recent'                               , via: :get
  match 'resumes/find_resume_in_given_date',to: 'resumes#find_resume_in_given_date'   , via: :get
  match 'resumes/upload_xls',to: 'resumes#upload_xls'                                 , via: :get
  match 'resumes/update_resume_likely_to_join',to: 'resumes#update_resume_likely_to_join'     , via: :get
  match 'resumes/process_xls_and_zipped_resumes',to: 'resumes#process_xls_and_zipped_resumes' , via: :get
  match 'resumes/close_requirement',to: 'resumes#close_requirement'                           , via: :get
  match 'resumes/export_interviews_per_date',to: 'resumes#export_interviews_per_date'         , via: :get
  match 'resumes/yto',to: 'resumes#yto'                                                       , via: :get
  match 'resumes/manager_yto',to: 'resumes#manager_yto'                                       , via: :get
  match 'resumes/show_quarterly_joined',to: 'resumes#show_quarterly_joined'                   , via: :get
  match 'resumes/show_all_joined_or_not_joined',to: 'resumes#show_all_joined_or_not_joined'   , via: :get
  match 'resumes/show_quarterly_offered',to: 'resumes#show_quarterly_offered'                 , via: :get
  match 'resumes/show_all_offered',to: 'resumes#show_all_offered'                             , via: :get
  match 'resumes/show_quarterly_not_accepted',to: 'resumes#show_quarterly_not_accepted'       , via: :get

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard_type_details.html.erb
<div id="show_requirements_description_div_<%= @status %>">
  <span class="span_with_13_with_padding_0"> <%= @status.titleize %>
    (<%= (@render == "manager_index") ? @forwards.size : @matches.size %>)
  </span>
  <% action = "export_as_xls_requirement_for_" + @status.downcase %>
  <%= link_to "Export", :host => APP_CONFIG['host_name'], :controller => "resumes", :action => action, :requirement_id => @requirement.id, :for_status => @status %>
  <% render_type = (@render == "interview_table") ? @render : "shared_" + @render %>
  <span class="span_with_padding_0_float">
    <%= link_to "Export", :host => APP_CONFIG['host_name'], :controller => "resumes", :action => action, :requirement_id => @requirement.id, :for_status => @status %>
  </span>
  <%= render "resumes/#{render_type}" %>
</div>

app/views/home/actions.html.erb
<div id="login_action_div" class="common_class">
  <%= link_to "Groups",       :host => APP_CONFIG['host_name'], :controller => "groups"       %> <br />
  <%= link_to "Requirements", :host => APP_CONFIG['host_name'], :controller => "requirements" %> <br />
  <%= link_to "Portals",      :host => APP_CONFIG['host_name'], :controller => "portals"      %> <br />
  <%= link_to "Agencies",     :host => APP_CONFIG['host_name'], :controller => "agencies"     %> <br />
</div>

app/views/home/advanced_search.html.erb
<br /> <br />
<%= form_tag(url_for(:host => APP_CONFIG['host_name'], :controller => "home", :action => "advanced_search_results"), :method => "get") do %>
  <table id="resume_form_table">
    <tr>
      <td> Search Pattern </td>
      <td> <%= text_field_tag :search %> </td>
    </tr>
    <tr>
      <td> Min Current CTC </td>
      <td>
        <%= text_field_tag :ctc_min %> <br />
        <span class="span_with_grey_color"> Enter in lakhs </span>
      </td>
    </tr>
    <tr>
      <td> Max Current CTC </td>
      <td>
        <%= text_field_tag :ctc_max %> <br />
        <span class="span_with_grey_color"> Enter in lakhs </span>
      </td>
    </tr>
    <tr>
      <td> Min Expected CTC </td>
      <td>
        <%= text_field_tag :expected_ctc_min %> <br />
        <span class="span_with_grey_color"> Enter in lakhs </span>
      </td>
    </tr>
    <tr>
      <td> Max Expected CTC </td>
      <td>
        <%= text_field_tag :expected_ctc_max %> <br />
        <span class="span_with_grey_color"> Enter in lakhs </span>
      </td>
    </tr>
    <tr>
      <td> Min Experience </td>
      <td>
        <%= select_tag "experience_years_min",   options_for_select(get_experience_years),  :class => "two_tds_same_line" %> Yrs
        <%= select_tag "experience_months_min",  options_for_select(get_experience_months), :class => "two_tds_same_line" %> Months
      </td>
    </tr>
    <tr>
      <td> Max Experience </td>
      <td>
        <%= select_tag "experience_years_max",   options_for_select(get_experience_years),  :class => "two_tds_same_line" %> Yrs
        <%= select_tag "experience_months_max",  options_for_select(get_experience_months), :class => "two_tds_same_line" %> Months
      </td>
    </tr>
    <tr>
      <td> Status </td>
      <td>
        <%= select_tag "status",   options_for_select(Resume.get_resume_statuses),  :class => "two_tds_same_line" %>
      </td>
    </tr>
    <tr>
      <td> Requirement </td>
      <td>
        <%= select_tag "requirement", options_for_select(Requirement.get_all_requirement_array_for_select) %>
      </td>
    </tr>
    <tr>
      <td> &nbsp; </td>
      <td class="add_resume_submit_button"> <%= submit_tag "Search" %> </td>
    </tr>
  </table>
<% end %>

<br /> <br />

app/views/home/advanced_search_results.html.erb
<div id="resume_search_div" class="common_class">
  <% if @results.size > 0 %>
    <div id="search_results_summary">
      <div id="searched_results_description">
        <% unless @search_text.nil? %>
          Search parameters - <%= @search_text %>
        <% end %>
      </div>
      <%= will_paginate @results, { :params => {:host => APP_CONFIG['host_name'], :only_path => false}} %>
      <%= hidden_field_tag "search", :value => @search_text %>
      <%= hidden_field_tag "ctc_min", :value => @ctc_min %>
      <%= hidden_field_tag "ctc_max", :value => @ctc_max %>
      <%= hidden_field_tag "expected_ctc_min", :value => @expected_ctc_min %>
      <%= hidden_field_tag "expected_ctc_max", :value => @expected_ctc_max %>
      <%= hidden_field_tag "experience_months_min", :value => @experience_months_min %>
      <%= hidden_field_tag "experience_months_max", :value => @experience_months_max %>
      <%= hidden_field_tag "status", :value => @status ? @status : "Any" %>
      <table>
        <tr>
          <th class="search_resume_name">      Name                </th>
          <th class="search_resume_qual">      Qualification       </th>
          <th class="search_resume_skills">    Skills/Summaries    </th>
          <th class="search_resume_status">    Overall Status      </th>
          <th class="search_resume_activity">  Recent Activity On  </th>
        </tr>
        <% @results.each do |result| %>
          <tr class="<%= cycle('result_line_odd', 'result_line_even') %>" >
            <td class="search_resume_name" title="<%= result.name %>">
              <div class="search_resume_name_div">
                <%= resume_link_with_20_characters(result) %>
              </div>
            </td>
            <td class="search_resume_qual" title="<%= result.qualification %>">
              <%= result.qualification[0..20] %>
            </td>
            <td class="search_resume_skills" title="<%= result.summary %>">
              <%= result.summary[0..20] %>
            </td>
            <td class="search_resume_status">
              <%= result.resume_overall_status %>
            </td>
            <td class="search_resume_activity">
              <% if result.comments.size > 0 %>
                <%= print_date(result.comments.last.updated_at) %>
              <% else %>
                <%= print_date(result.updated_at) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= will_paginate @results, { :params => {:host => APP_CONFIG['host_name'], :only_path => false}} %>
  <% else %>
    <span class="span_with_13_with_padding_0"> Sorry there are no results found corresponding to your search parameters. </span>
  <% end %>
</div>

app/views/home/dashboard.html.erb
<h2> My Dashboard </h2>
<div class="common_class">
  <table>
    <thead>
      <tr class="header_row">
        <td> New         </td>
        <td> Forwards    </td>
        <td> Shortlisted </td>
        <td> Scheduled   </td>
        <td> Rejected    </td>
        <td> Holds       </td>
        <td> Eng Select  </td>
        <td> HAC         </td>
        <td> YTO         </td>
        <td> Offered     </td>
        <td> Joining     </td>
      </tr>
    </thead>
    <tbody>
      <tr class="blue">
        <td> <%= link_to @new.size, :host => APP_CONFIG['host_name'], :controller=> "resumes", :action => "new_resumes", :mine => "true" %>   </td>
        <td> <%= link_to @forwards.size,   :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "forwarded", :mine => "true"%>   </td>
        <td> <%= link_to @shortlists.size,   :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "shortlisted", :mine => "true"%>   </td>
        <td> <%= link_to @scheduled.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "interviews_status", :mine => "true"%>   </td>
        <td> <%= link_to @rejected.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "rejected", :mine => "true"%>   </td>
        <td> <%= link_to @holds.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "hold", :mine => "true"%>   </td>
        <td> <%= link_to @eng_selects.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "eng_select", :mine => "true"%>   </td>
        <td> <%= link_to @hacs.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "hac", :mine => "true"%>   </td>
        <td> <%= link_to @ytos.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "yto", :mine => "true"%>   </td>
        <td> <%= link_to @offered.size,    :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "offered", :mine => "true"%>   </td>
        <td> <%= link_to @joining.size,      :host => APP_CONFIG['host_name'], :controller => "resumes", :action => "joined", :mine => "true"%>   </td>
      </tr>
    </tbody>
  </table>
  <% unless @status.nil? %>
    <%= render home/dashboard_type %>
  <% end %>
</div>

app/views/home/index.html.erb
<div id="employees_login_div" class="common_class">
  <div id="login_form">
    <span class="login_desc_line"> Login to your recruitment account </span>
    <% url = url_for :action => "login", :controller => "employees", :only_path => false, :port => false%>
    <%= form_with url:url do |form| %>
      <table>
        <tr>
          <td class="login_text"> <label for="login_text"> Mirafra user name </td>
        </tr>
        <tr>
          <td class="login_field">
            <%= form.text_field :login %>
          </td>
        </tr>
        <tr>
          <td class="login_text"> <label for="login_text"> Password </td>
        </tr>
        <tr>
          <td class="login_field">
            <%= password_field_tag :password, params[:password], :value => "Password", :onfocus => "textBoxContentsOnFocus(this.id, 'Password');", :onblur => "textBoxContentsOnBlur(this.id, 'Password');"  %>
          </td>
        </tr>
        <tr>
          <td class="login_submit_button">
            <%= submit_tag( "Go" ) %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>
<script>
  $(document).ready(() => { $('#login').focus() });
</script>

app/views/home/interview_panels.html.erb
<div class="interview-panel">
<h1 class="interview-panel__title">Interview Panels</h1>
<br>
<div>
  <%= form_tag(url_for(:host => APP_CONFIG['host_name'], :controller => "interview_skills", :action => "create"), :method => "post") do %>
    <label for="skill"> Add new skill:</label>
    <%= text_field_tag :skill %> 
    <%= submit_tag "Submit" %> 
  <% end %>
</div>
<br>

<div>
  <label for="Search"> Search Skill</label>
  <input type="text" id="search_skill" name="skill" value="">
  <input type="submit" value="Search" id="search_skill_submit" onclick="search()">
</div>
<br>

<%@skills.each do |skill|  %>
  <div class="skill_container" data-skill-name= "<%= skill.name %>">
    <div class="skill">
      <span class= "skill-name"><%= skill.name %></span>
      <span>
        <%= form_tag(url_for(:host => APP_CONFIG['host_name'], :controller => "interview_skills", :action => "add_interviewer"), :method => "post") do %>
          <span class="add-interviewer">Add new interviewer:</span>   <input type="text" class="new-interviewer" name="new_interviewer" value="" required="required">
          <%= hidden_field_tag "skill_id", skill.id %>
          <%= submit_tag "Add" %> 
        <% end %>
      </span>
    </div>  
    
    <table class= "int-table table" style="width:100%">
      <tr>
        <th class="int-th">Name</th>
        <th class="int-th">Interviews</th> 
        <th class="int-th">Slots/week</th>
        <th class="int-th">Preferred Day/time</th> 
        <th class="int-th">Email</th> 
        <th class="int-th">Phone</th>
        <th class="int-th">Customer</th> 
        <th class="int-th">Action</th>
      </tr>
      <% skill.interviewers.each do |interviewer|%>
        <tr>
          <td class="t-data"><%=interviewer.name %></td>
          <td class="t-data" ><%= interviewer.interviews.next_week %></td>
          <td class="t-data" >
            <span id=<%= "#{skill.id}-#{interviewer.eid}"%>> <%= interviewer.n_interviews_per_week %> <%= link_to image_tag("edit.svg", :size => "15x15"),'#', onclick: "toggleElement(event,'##{skill.id}-#{interviewer.eid}')", title:"Edit" %></span>
            <%= form_tag(url_for(:host => APP_CONFIG['host_name'], :controller => "employees", :action => "edit_slot"), :method => "post", :id => "#{skill.id}-#{interviewer.eid}-form",style: "display:none;") do %>
              <input type="number" class="edit_slot" name="n_interviews_per_week" value=<%= interviewer.n_interviews_per_week %>>
              <%= hidden_field_tag "interviewer_id", interviewer.id %>
              <%= submit_tag "update" %> 
            <% end %>
          </td>
          <td class="t-data" > 
            <span id=<%= "#{skill.id}-#{interviewer.eid}-pref-date"%>> <%= interviewer.preferred_day_and_time %> 
            <% if is_HR? %>
              <%= link_to image_tag("edit.svg", :size => "15x15"),'#', onclick: "toggleElement(event,'##{skill.id}-#{interviewer.eid}-pref-date')", title:"Edit" %>
            <% end %>
            </span>
            <%= form_tag(url_for(:host => APP_CONFIG['host_name'], :controller => "employees", :action => "edit_slot"), :method => "post", :id => "#{skill.id}-#{interviewer.eid}-pref-date-form",style: "display:none;") do %>
              <textarea rows="3" class="" name="preferred_day_and_time">
                <%= interviewer.preferred_day_and_time %>
              </textarea>
              <%= hidden_field_tag "interviewer_id", interviewer.id %>
              <%= submit_tag "update" %> 
            <% end %>
          </td>
          <td class="t-data" > <%= interviewer.email %></td>
          <td class="t-data"> <%= interviewer.phone %> </td>
          <td class="t-data customer-<%=interviewer.eid%>" >Not Found</td>
          <td><span class="close_box_link">
            <%= link_to image_tag("RedCross.png", :size => "22x22"),url_for(:host => APP_CONFIG['host_name'], controller: :interview_skills, action: :destroy,id: interviewer.id, skill_id: skill.id),method: :delete, data: {confirm: "Are you sure you want to remove interviewer?"},title: "delete" %>
          </span> <br /></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>
</div>
<% url = "https://" + APP_CONFIG['host_name'] + employees_autocomplete_path %>
<% rms_base_url = "https://" + APP_CONFIG['rms_host_name'] %>

<script>
  $('.new-interviewer').autocomplete({
    source: function(request, response) {
      $.ajax({
        url: '<%=url%>',
        dataType: "json",
        data: {
          query: request.term
        },
        success: function(data) {
          response(data);
        }
      });
    }
  });

  $.ajax({
    url: '<%= rms_base_url + "/customer_data" %>', //TODO: RMS URL
    type: 'GET',
    data:{employee_id:<%= @eids %>},
    success: function (response) {
        $.each(response, function (i, item) {
          let k = 0;
          htmlElements = document.querySelectorAll(".customer-"+item.eid);
          while(k < htmlElements.length) {
            htmlElements[k].innerHTML = item.customer;
            k+=1;
          }
        });
      
    }
  });

  function search (){
    var skills = document.querySelectorAll('[data-skill-name]');
    var i = 0;
    var searchTerm =document.getElementById("search_skill").value.toLowerCase();
    while (i < skills.length) {
      var skillName= skills[i].getAttribute('data-skill-name').toLowerCase();
      if (skillName.includes(searchTerm)) {
        skills[i].style.display="block"
      } else {
          skills[i].style.display="none"
      }
      i+=1;
    }
  }

  function toggleElement(e, element){
    e.preventDefault();
    $(element).toggle();
    $(element+"-form").toggle();
  }
</script>

app/views/home/search.html.erb
<div id="resume_search_div" class="common_class">
  <% if @results.size > 0 %>
    <div id="search_results_summary">
      <div id="searched_results_description">
        <% unless @search_text.nil? %>
          Search parameters - <%= @search_text %>
        <% end %>
      </div>
      <%= will_paginate @results, { :params => {:host => APP_CONFIG['host_name'], :only_path => false}} %>
      <%= hidden_field_tag "search[box]", :value => @search_text %>
      <table>
        <tr>
          <th class="search_resume_name">      Name                </th>
          <th class="search_resume_qual">      Qualification       </th>
          <th class="search_resume_skills">    Skills/Summaries    </th>
          <th class="search_resume_status">    Overall Status      </th>
          <th class="search_resume_activity">  Recent Activity On  </th>
        </tr>
        <% @results.each do |result| %>
          <tr class="<%= cycle('result_line_odd', 'result_line_even') %>" >
            <td class="search_resume_name" title="<%= result.name %>">
              <div class="search_resume_name_div">
                <%= resume_link_with_20_characters(result) %>
              </div>
            </td>
            <td class="search_resume_qual" title="<%= result.qualification %>">
              <%= result.qualification[0..20] %>
            </td>
            <td class="search_resume_skills" title="<%= result.summary %>">
              <%= result.summary[0..20] %>
            </td>
            <td class="search_resume_status">
              <%= result.resume_overall_status %>
            </td>
            <td class="search_resume_activity">
              <% if result.comments.size > 0 %>
                <%= print_date(result.comments.last.updated_at) %>
              <% else %>
                <%= print_date(result.updated_at) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= will_paginate @results, { :params => {:host => APP_CONFIG['host_name'], :only_path => false}} %>
  <% else %>
    <span class="span_with_13_with_padding_0"> Sorry there are no results found corresponding to your search parameters. </span>
  <% end %>
</div>

app/views/home/summaries.html.erb
<div id="summaries_home" class="common_class">
  <ul>
    <li> <%= link_to "Interviewer Summary", {:host => APP_CONFIG['host_name'],  :controller => "home", :action => "show_summary_per_interviewer" } %> </li>
    <li> <%= link_to "Recruiter Summary",   {:host => APP_CONFIG['host_name'],  :controller => "home", :action => "show_summary_per_recruiter" } %>   </li>
    <li> <%= link_to "Manager Summary",     {:host => APP_CONFIG['host_name'],  :controller => "home", :action => "show_summary_per_manager" } %>     </li>
  </ul>
</div>